### ISSUE TITLE
WindChanger doesn't create needed files.

### ISSUE THREAD

**Issue by officialfatjesus** [hytonhan/Timberborn-WindPlugin#1]
I've installed all required files, ran the games once, exited, can't find the config files. Looked in BepInExPack_Timberborn, Documents, the game data folder. Even did a search on both of my SSDs.

**Comment by hytonhan** [comment]
Resolved in Timberborn Discord server. The config is in BepInEx config folder. Its name is hytone.plugins.windplugin.cfg. Easiest way to edit the config is thru thunderstore mod manager "Config editor" tab
